---
- name: Agregar la key de Anydesk
  become: true
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present
  register: anydesk_repo_key

- name: Agregar repositorio de Anydesk
  become: true
  apt_repository:
    repo: "deb http://deb.anydesk.com/ all main"
  register: anydesk_repo

- name: Actualizar repositorios para instalar Anydesk
  apt:
    update_cache: true
  become: true
  when: anydesk_repo.changed or anydesk_repo_key.changed

- name: Install AnyDesk
  apt:
    name: anydesk
    state: present
  become: true
  notify:
    - Restart Anydesk service

- name: Allow unattended access
  lineinfile:
    path: /etc/anydesk/system.conf
    regexp: '^ad.security.interactive_access='
    line: ad.security.interactive_access=0
  become: true

# Luego de instalar
# echo <some_password> | sudo anydesk --set-password and anydesk --get-id
