---
- name: install VSCode
  vars:
    vscode_extension_list:
    ## Convert Tool
     - ahebrank.yaml2json
     - buianhthang.xml2json


- name: install a list of extension
  shell: code --install-extension {{ item }}
  become: yes
  become_user: "{{ ansible_user_id }}"
  with_items: "{{vscode_extension_list}}"


# TO-DO

# Make Visual Studio Code default plain-text editor.
# xdg-mime default code.desktop text/plain

# Configure Visual Studio Code.
# yes | cp -rf ./static/vscode/{settings.json,keybindings.json} ~/.config/Code/User/
# yes | cp -rf ./static/text/{pycodestyle,flake8} ~/.config/
