---
- name: download and install visual studio code
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  when: ansible_userspace_architecture == 'x86_64'

- name: install a list of extension
  shell: code --install-extension {{ item }}
  become: yes
  become_user: "{{ ansible_user_id }}"
  with_items: "{{vscode_extension_list}}"


# TO-DO

# Make Visual Studio Code default plain-text editor.
# xdg-mime default code.desktop text/plain

# Configure Visual Studio Code.
# yes | cp -rf ./static/vscode/{settings.json,keybindings.json} ~/.config/Code/User/
# yes | cp -rf ./static/text/{pycodestyle,flake8} ~/.config/
