---
- name: Descargar e instalar Visual Studio Code
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  when: ansible_userspace_architecture == 'x86_64'

- name: Instalar muchas extensiones predefinidas
  become: false
  become_user: "{{ ansible_user_id }}"
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extension_list }}"

- name: Definir visual studio code como editor de texto predeterminado
  command: "xdg-mime default code.desktop {{ text_types }}"
  when: false
  with_items: "{{ text_types }}"
  vars:
    text_types:
      - text
      - text/plain
      - text/markdown
      - application/x-yaml
      - text/x-python
