---
- name: Instalar paquetes de sistema, drivers
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - htop
      - mc
      - tmux
      - ubuntu-restricted-extras
      - apt-transport-https
      - curl
      - wget
      - openssh-client
      - openssh-server
      - jq
      - tldr
      - ppa-purge
      - locate

- name: Utilidades de compresi칩n
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - zip
      - gzip
      - tar
      - unrar
      - unzip
      - p7zip-full
      - p7zip-rar

- name: Instalar otras aplicaciones
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - poedit
      - fail2ban
      - ufw
      - vlc
      - ffmpeg

- name: An치lisis de Hardware, informaci칩n del sistema
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - htop
      - inxi
      - hwinfo
      - glances
      - mtr
      - hardinfo
      - stacer

- name: Improve battery performance
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    pkg:
      - tlp
      - tlp-rdw
      - acpi-call-dkms
      - powertop

- name: Paquetes varios de entorno gr치fico
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - indicator-multiload
      - alacarte
      - fonts-firacode
      - gnome-tweak-tool
