---
- name: Sysadmin - Instalar extensiones predefinidas de visual studio code
  become: true
  become_user: "{{ remote_regular_user }}"
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extension_list_sysadmin }}"
  changed_when: False