---
- name: Agregar la key de Terraform
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Agregar repositorio de Terraform
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    state: present

- name: Instalar Terraform
  become: true
  apt:
    name: terraform
