---
- name: Agregar la key de Terraform
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Agregar repositorio de Terraform
  become: true
  apt_repository:
    repo: deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main
    filename: terraform

- name: Instalar Terraform
  become: true
  apt:
    name: terraform
