---
# Es bastante específico, pero usamos vagrant para testear los roles y tasks de ansible
- name: Instalar virtualbox
  become: true
  apt:
    name: virtualbox

- name: Agregar la key de Vagrant
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Agregar repositorio de Vagrant
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com stable main"
    filename: vagrant

- name: Instalar Vagrant
  become: true
  apt:
    name: vagrant
