---
- name: Agregar la key de Anydesk
  become: true
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present
  register: anydesk_repo_key

- name: Agregar repositorio de Anydesk
  become: true
  apt_repository:
    repo: "deb http://deb.anydesk.com/ all main"
  register: anydesk_repo

- name: Actualizar repositorios para instalar Anydesk
  become: true
  apt:
    update_cache: true
  when: anydesk_repo.changed or anydesk_repo_key.changed

- name: Install AnyDesk
  become: true
  apt:
    name: anydesk
    state: present


- name: Reiniciar servicio
  become: true
  systemd:
    name: anydesk.service
    state: restarted

- name: Allow unattended access
  become: true
  lineinfile:
    path: /etc/anydesk/system.conf
    regexp: '^ad.security.interactive_access='
    line: ad.security.interactive_access=0
