---
# Configuring Ext
- name: Configurando ext 01
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/wsmatrix/num-columns"
    value: "2"
    state: present

- name: Configurando ext 02
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/wsmatrix/num-rows"
    value: "2"
    state: present

- name: Configurando ext 03
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/wsmatrix/show-overview-grid"
    value: "true"
    state: present

- name: Configurando ext 04
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/city"
    value: "'-32.9575, -60.639444>Rosario, Santa Fe>-1'"
    state: present

- name: Configurando ext 05
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/unit"
    value: "'celsius'"
    state: present

- name: Configurando ext 06
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/wind-speed-unit"
    value: "'m/s'"
    state: present

- name: Configurando ext 07
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/pressure-unit"
    value: "'hPa'"
    state: present

- name: Configurando ext 08
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/scroll-action"
    value: "'cycle-windows'"
    state: present

- name: Configurando ext 09
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces"
    value: "true"
    state: present

- name: Configurando ext 10
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor"
    value: "true"
    state: present

- name: Configurando ext 11
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/window-switcher/current-workspace-only"
    value: "true"
    state: present

- name: Configurando ext 12
  become: false
  community.general.dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: present

- name: Configurando ext 13
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
    state: present

- name: Configurando ext 14
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present

- name: Configurando ext 15
  become: false
  community.general.dconf:
    key: "/org/gnome/mutter/dynamic-workspaces"
    value: "false"
    state: present

- name: Configurando ext 16
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/num-workspaces"
    value: "4"
    state: present
