---
# Add Fav Apps
- name: Agregar apps al panel lateral
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop']"

# Make Nautilus capable of browse recursively
- name: Agregar repositorio para nautilus
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:lubomir-brindza/nautilus-typeahead

- name: Actualizar nautilus a latest
  become: true
  apt:
    name: indicator-sound-switcher

- name: Actualizar nautilus a latest
  become: true
  apt:
    name: nautilus
    state: latest
    update_cache: true

- name: Enable nautilus location
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/nautilus/preferences/always-use-location-entry"
    value: "true"

- name: Enable nautilus interactive search
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/nautilus/preferences/enable-interactive-search"
    value: "true"

- name: Configurar DNS
  net_system:
    name_servers:
      - 8.8.8.8
      - 8.8.4.4
