---
- name: Instalar dependencias para configurar Gnome
  become: true
  apt:
    pkg: ['python3-psutil']

- name: GNOME Preferences - Shell - Attach Modal Dialogues
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/overrides/attach-modal-dialogs"
    value: "false"
    state: present

- name: GNOME Preferences - Nautilus - Clock Format
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present

- name: Agregar repositorio para indicator-keylock
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:tsbarnes/indicator-keylock

- name: Instalar indicator-keylock
  become: true
  apt:
    name: indicator-keylock
  tags:
    - indicator-keylock

- name: Agregar repositorio para indicator-sound-switcher
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:yktooo/ppa

- name: Instalar indicator-sound-switcher
  become: true
  apt:
    name: indicator-sound-switcher

# Install the Extensions using https://github.com/cyfrost/install-gnome-extensions/
- name: Descargar script para instalar gnome extensions
  get_url:
    url: https://raw.githubusercontent.com/cyfrost/install-gnome-extensions/master/install-gnome-extensions.sh
    dest: /tmp/install-gnome-extensions.sh
    mode: '+x'

- name: Instalar gnome extensions
  become: true
  become_user: "{{ remote_regular_user }}"
  script: /tmp/install-gnome-extensions.sh --overwrite --enable 1485 1301 921 6 8 750