---
- name: Instalar dependencias para configurar Gnome
  become: true
  apt:
    pkg: ['python3-psutil']

- name: GNOME Preferences - Shell - Attach Modal Dialogues
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/overrides/attach-modal-dialogs"
    value: "false"
    state: present

- name: GNOME Preferences - Nautilus - Clock Format
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present

- name: Agregar repositorio para indicator-keylock
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:tsbarnes/indicator-keylock

- name: Instalar indicator-keylock
  become: true
  apt:
    name: indicator-keylock
  tags:
    - indicator-keylock

- name: Agregar repositorio para indicator-sound-switcher
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:yktooo/ppa

- name: Instalar indicator-sound-switcher
  become: true
  apt:
    name: indicator-sound-switcher

- name: Copy wallpaper
  copy: src=files/isotipo_adhoc.png dest=/home/{{ remote_regular_user }}/.wallpaper.jpg owner={{ remote_regular_user }} group={{ remote_regular_user }} mode=600

- name: Setear GNOME wallpaper
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ remote_regular_user }}/.wallpaper.jpg'"

- name: Copiar lockscreenfile
  copy: src=files/logotipo_adhoc.png dest=/home/{{ remote_regular_user }}/.logotipo_adhoc.png owner={{ remote_regular_user }} group={{ remote_regular_user }} mode=600

- name: Setear lock screen background
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///home/{{ remote_regular_user }}/.logotipo_adhoc.png'"

- name: Centrar lock screen background
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'centered'"

- name: Setear background colour
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/primary-color"
    value: "'#d6d6d4'"

- name: Mejorar performance de UI - Show seconds
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "'false'"

- name: Mejorar performance de UI - Disable animations
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "'false'"

- name: Mejorar performance de UI - Set GTK theme
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
    state: present

- name: Mejorar performance de UI - Set cursor theme
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'DMZ-Black'"
    state: present

- name: Mejorar performance de UI - Set icon theme
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'ubuntu-mono-dark'"
    state: present

# Determina si el cambio entre áreas de trabajo debería suceder para las ventanas en todos los monitores o sólo para ventanas en el monitor primario.
- name: Mejorar performance de UI - Workspaces on primary screen
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "'true'"
    state: present

# Shortcuts
- name: Shortcuts Move 01
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1"
    value: "['<Shift><Super>F1']"

- name: Shortcuts Move 02
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2"
    value: "['<Shift><Super>F2']"

- name: Shortcuts Move 03
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3"
    value: "['<Shift><Super>F3']"

- name: Shortcuts Move 04
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4"
    value: "['<Shift><Super>F4']"

- name: Shortcuts Switch 01
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
    value: "['<Super>F1']"

- name: Shortcuts Switch 02
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
    value: "['<Super>F2']"

- name: Shortcuts Switch 03
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
    value: "['<Super>F3']"

- name: Shortcuts Switch 04
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
    value: "['<Super>F4']"

# Add Fav Apps
- name: Agregar apps al panel lateral
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop']"

# Install the Extensions using https://github.com/cyfrost/install-gnome-extensions/
- name: Descargar script para instalar gnome extensions
  get_url:
    url: https://raw.githubusercontent.com/cyfrost/install-gnome-extensions/master/install-gnome-extensions.sh
    dest: /tmp/install-gnome-extensions.sh
    mode: '+x'

- name: Instalar gnome extensions
  become: true
  become_user: "{{ remote_regular_user }}"
  script: /tmp/install-gnome-extensions.sh --overwrite --enable 1485 1301 921 6 8 750