---
- name: Instalar dependencias para configurar Gnome
  apt:
    name: python3-psutil
    state: present
    update_cache: true

- name: GNOME Preferences - Shell - Attach Modal Dialogues
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {key: "/org/gnome/shell/overrides/attach-modal-dialogs", value: "false"}
    - {key: "/org/gnome/desktop/interface/clock-format", value: "'24h'"}

# Install the Extensions using https://github.com/cyfrost/install-gnome-extensions/
- name: Descargar script para instalar gnome extensions
  get_url:
    url: https://raw.githubusercontent.com/cyfrost/install-gnome-extensions/master/install-gnome-extensions.sh
    dest: /tmp/install-gnome-extensions.sh
    mode: '+x'

- name: Instalar gnome extensions
  become_user: "{{ remote_regular_user }}"
  script: /tmp/install-gnome-extensions.sh --overwrite --enable 6 8 36 750 906 921 1485 3763 4362
  changed_when: false
# 6/applications-menu/
# 8/places-status-indicator/
# 36/lock-keys/
# 750/openweather/
# 906/sound-output-device-chooser/
# 921/multi-monitors-add-on/
# 1485/workspace-matrix/
# 3763/battery-status/
# 4362/fullscreen-avoider/
