---
- name: Instalar dependencias para configurar Gnome
  become: true
  apt:
    pkg: ['python3-psutil']

- name: GNOME Preferences - Shell - Attach Modal Dialogues
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {key: "/org/gnome/shell/overrides/attach-modal-dialogs", value: "false"}
    - {key: "/org/gnome/desktop/interface/clock-format", value: "'24h'"}

- name: Agregar repositorios para indicator-keylock e indicator-sound-switcher
  become: true
  apt_repository:
    repo: "{{ item.repo }}"
  with_items:
    - {repo: ppa:tsbarnes/indicator-keylock}
    - {repo: ppa:yktooo/ppa}

- name: Instalar indicator-keylock e indicator-sound-switcher
  become: true
  apt:
    pkg:
      - indicator-keylock
      - indicator-sound-switcher

# Install the Extensions using https://github.com/cyfrost/install-gnome-extensions/
- name: Descargar script para instalar gnome extensions
  get_url:
    url: https://raw.githubusercontent.com/cyfrost/install-gnome-extensions/master/install-gnome-extensions.sh
    dest: /tmp/install-gnome-extensions.sh
    mode: '+x'

- name: Instalar gnome extensions
  become: true
  become_user: "{{ remote_regular_user }}"
  script: /tmp/install-gnome-extensions.sh --overwrite --enable 1485 1301 921 6 8 750 3763
  changed_when: false
