---
- hosts: all
  vars_files:
    - ./vars/vars.yml
  become: true

  tasks:
  - import_tasks: anydesk.yml
  - import_tasks: chrome.yml
  - import_tasks: ext.yml
  - import_tasks: gnome.yml
  - import_tasks: language.yml
  - import_tasks: meld.yml
  - import_tasks: packages.yml
