---
- name: Base - Instalar paquetes de sistema, drivers
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - htop
      - mc
      - tmux
      - ubuntu-restricted-extras
      - apt-transport-https
      - curl
      - wget
      - openssh-client
      - openssh-server
      - jq
      - tldr
      - ppa-purge
      - locate
      - libxshmfence1

- name: Base - Utilidades de compresión
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - zip
      - gzip
      - tar
      - unrar
      - unzip
      - p7zip-full
      - p7zip-rar

- name: Base - Instalar otras aplicaciones
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - poedit
      - fail2ban
      - ufw
      - vlc
      - ffmpeg

- name: Base - Análisis de Hardware, información del sistema
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - htop
      - inxi
      - hwinfo
      - glances
      - mtr
      - hardinfo
      - stacer

- name: Base - Performance y  rendimiento de batería
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - tlp
      - tlp-rdw
      - acpi-call-dkms
      - powertop

- name: Base - Paquetes varios de entorno gráfico, captura de pantalla, etc.
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - indicator-multiload
      - alacarte
      - fonts-firacode
      - flameshot

- name: Instalar gnome tweaks (20.04)
  apt:
    name: gnome-tweak-tool
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Instalar gnome tweaks (22.04)
  apt:
    name: gnome-tweaks
    state: present
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'