- name: Mejorar performance de UI - Show seconds
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "'false'"

- name: Mejorar performance de UI - Disable animations
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "'false'"

- name: Mejorar performance de UI - Set GTK theme
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
    state: present

- name: Mejorar performance de UI - Set cursor theme
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'DMZ-Black'"
    state: present

- name: Mejorar performance de UI - Set icon theme
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'ubuntu-mono-dark'"
    state: present

# Determina si el cambio entre áreas de trabajo debería suceder para las ventanas en todos los monitores o sólo para ventanas en el monitor primario.
- name: Mejorar performance de UI - Workspaces on primary screen
  become: true
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "'true'"
    state: present