---
- name: Docker - Instalar dependencias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Docker - Agregar GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Agregar repositorio
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Docker - Instalar
  apt:
    name: docker.io
    update_cache: "yes"
    state: present

- name: Docker - Instalar docker compose plugin
  apt:
    name: docker-compose-plugin
    update_cache: "yes"
    state: present

- name: Docker - Crear grupo docker
  group:
    name: docker
    state: present

- name: Docker - Agregar users al grupo
  user:
    name: "{{ remote_regular_user }}"
    groups: ["docker"]
    append: "yes"

- name: Docker - Instalar docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker-compose_version }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: '+x'
