---
- name: Docker - Instalar dependencias
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Docker - Agregar GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Agregar repositorio
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Docker - Instalar
  ansible.builtin.apt:
    name: docker.io
    update_cache: "yes"
  when: ansible_distribution_version == "20.04" and ansible_os_family == "Debian"

- name: Docker - Instalar docker compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    update_cache: "yes"
  when: ansible_distribution_version == "20.04" and ansible_os_family == "Debian"

- name: Docker - Crear grupo docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker - Agregar users al grupo
  ansible.builtin.user:
    name: "{{ item }}"
    groups: ["docker"]
    append: "yes"
  loop: "{{ docker_users|flatten(levels=1) }}"
