---
- name: Docker - Instalar dependencias
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Docker - Agregar GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Agregar repositorio
  apt_repository:
    repo: "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    state: present

- name: Docker - Instalar
  ansible.builtin.apt:
    name: docker.io
    update_cache: "yes"
    state: present

- name: Docker - Instalar docker compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    update_cache: "yes"
    state: present

- name: Docker - Crear grupo docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker - Agregar users al grupo
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: ["docker"]
    append: "yes"
