---
# Fuente: https://graspingtech.com/install-docker-ansible/
# Revisar docker-compose version in /tasks/vars.yml
- name: Instalar dependencias de docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Agregar docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar repositorio de docker
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Instalar docker
  ansible.builtin.apt:
    name: docker.io
    update_cache: "yes"
  when: ansible_distribution_version == "20.04" and ansible_os_family == "Debian"

- name: Habilitar e iniciar docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Crear grupo docker
  group:
    name: "docker"
    state: present

- name: Agregar usuario al grupo docker
  user:
    name: "{{ remote_regular_user }}"
    groups: docker
    append: true
