---
- name: Editor de texto, colorizer, terminal
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - vim
      - vim-gtk3
      - ccze
      - tmux
      - tmuxp
      - xclip
      - bash-completion
      - yakuake

- name: Yakuake - Configuraciones
  copy:
    src: ./files/yakuakerc
    dest: ~/.config/
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: '0666'

- name: Yakuake - Directorio para configuración
  file:
    path: ~/.local/share/konsole
    state: directory
    mode: "774"

- name: Yakuake - Copiar archivo configuración
  copy:
    src: ./files/Profile_1.profile
    dest: ~/.local/share/konsole
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "0666"

- name: Python - Instalar dependencias y paquetes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - ipython3
      - python3-setuptools
      - python-setuptools
      - python-pip-whl
      - python3-pip
      - python3
