# Workarounds y parches para preparar el ambiente local de desarrollo
- name: Local dev - Corregir permisos de volúmenes
  file:
    path: /var/lib/docker/volumes/
    recurse: true
    state: directory
    mode: 'g+rwx'

- name: Local dev - Agregar user al grupo root
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: ["root"]
    append: "yes"

# Descargar, instalar, levantar odoo 13 y 15
- name: Ansible - Variable para verificar si está la carpeta odoo
  stat:
    path: /home/{{ remote_regular_user }}/odoo
    register: odoo_folder

- name: Local dev - ¿Existe la carpeta odoo?
  debug:
    msg: "La carpeta Odoo ya había sido clonada / creada"
    when: odoo_folder.stat.exists

- name: Local dev - Crear carpeta local para Odoo
  become: false
  file:
    path: /home/{{ remote_regular_user }}/odoo
    state: directory
    when: my_folder.stat.exists == false

- name: Local dev - Clonar repositorio de Odoo v13
  become: false
  git:
    repo: https://github.com/ingadhoc/docker-compose-odoo.git
    dest: /home/{{ remote_regular_user }}/odoo/13
    clone: yes
    update: yes

- name: Local dev - Editar odoo_minor de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^ODOO_MINOR="
    line: "ODOO_MINOR=13.0-enterprise"
    state: present

- name: Local dev - Editar domain de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^DOMAIN="
    line: "DOMAIN=13.odoo.localhost"
    state: present

- name: Local dev - Editar odoo_version de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^ODOO_VERSION="
    line: "ODOO_VERSION=13"
    state: present

- name: Local dev - Clonar repositorio de Odoo v15
  become: false
  git:
    repo: https://github.com/ingadhoc/docker-compose-odoo.git
    dest: /home/{{ remote_regular_user }}/odoo/15
    clone: yes
    update: yes

- name: Local dev - Editar odoo_minor de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    regexp: "^ODOO_MINOR="
    line: "ODOO_MINOR=15.0-enterprise"
    state: present

- name: Local dev - Editar domain de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    regexp: "^DOMAIN="
    line: "DOMAIN=15.odoo.localhost"
    state: present

- name: Local dev - Editar odoo_version de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    regexp: "^ODOO_VERSION="
    line: "ODOO_VERSION=15"
    state: present
