# Workaround
# TODO: Improve this
sudo chmod -R g+rwx /var/lib/docker/volumes/
sudo adduser $USER root

# Download and install the last 3 versions of odoo
cd && mkdir -p odoo && cd odoo
ODOO_ACTIVE_VER=("11"  "12"  "13")
for ODOO_VER in  ${ODOO_ACTIVE_VER[*]}
do
    cd ~/odoo
    sudo rm -rf $ODOO_VER
    git clone https://github.com/ingadhoc/docker-compose-odoo.git $ODOO_VER && cd $ODOO_VER
    sed -i "s/DOMAIN=.*/DOMAIN=odoo${ODOO_VER}.loc/" .env
    sed -i "s/ODOO_MINOR=.*/ODOO_MINOR=${ODOO_VER}.0-enterprise/" .env
    sed -i "s/# DBFILTER/DBFILTER/" .env
    # Usamos localhost en lugar de loc para no tener que hacer movidas con los DNS.
    sed -ir 's/.loc\s/.localhost /' .env
    # Levantamos para crear los volumenes.
    sudo docker-compose run --rm odoo ls
    # docker-compose up -d
    # docker stop ${ODOO_VER}_odoo_1
    sudo ./scripts/initial_setup.sh
    # yes |sudo ./scripts/generate_custom
done
docker stop portainer
