# Workarounds y parches para preparar el ambiente local de desarrollo
- name: Corregir permisos de volúmenes
  file:
    path: /var/lib/docker/volumes/
    recurse: true
    state: directory
    mode: 'g+rwx'

- name: Agregar user al grupo root
  user:
    name: "{{ remote_regular_user }}"
    group: root

# Descargar, instalar, levantar odoo 13 y 15
- name: Crear carpeta local para Odoo
  file:
    path: /home/{{ remote_regular_user }}/odoo
    state: directory

- name: Clonar repositorio de Odoo v13
  git:
    repo: https://github.com/ingadhoc/docker-compose-odoo.git
    dest: /home/{{ remote_regular_user }}/odoo/13
    clone: yes
    update: yes

- name: Editar odoo_minor de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^ODOO_MINOR="
    line: "ODOO_MINOR=13.0-enterprise"
    state: present

- name: Editar domain de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^DOMAIN="
    line: "DOMAIN=13.odoo.localhost/"
    state: present

- name: Editar odoo_version de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/13/.env
    regexp: "^ODOO_VERSION="
    line: "ODOO_VERSION=13"
    state: present

- name: Levantar Odoo v13 + servicios
  docker_compose:
    project_src: /home/{{ remote_regular_user }}/odoo/13/
    state: absent

- name: Clonar repositorio de Odoo v15
  git:
    repo: git clone https://github.com/ingadhoc/docker-compose-odoo.git
    dest: /home/{{ remote_regular_user }}/odoo/15
    clone: yes
    update: yes

- name: Editar odoo_minor de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    # The String to Search
    regexp: "^ODOO_MINOR="
    # The String to Replace
    line: "ODOO_MINOR=15.0-enterprise"
    state: present

- name: Editar domain de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    # The String to Search
    regexp: "^DOMAIN="
    # The String to Replace
    line: "DOMAIN=15.odoo.localhost/"
    state: present

- name: Editar odoo_version de .env
  lineinfile:
    path: /home/{{ remote_regular_user }}/odoo/15/.env
    # The String to Search
    regexp: "^ODOO_VERSION="
    # The String to Replace
    line: "ODOO_VERSION=15"
    state: present

- name: Levantar Odoo v15 + servicios
  docker_compose:
    project_src: /home/{{ remote_regular_user }}/odoo/15/
    state: absent
