---
- name: Instalar pip3
  become: true
  apt:
    name: python3-pip

- name: Instalar PyLint for Python 3
  become: true
  apt:
    name: pylint3
    state: present

- name: Instalar pylint for odoo
  pip:
    name: pylint-odoo
    extra_args: --upgrade --pre

- name: Instalar flake8
  become: true
  pip:
    name: flake8

- name: Instalar pep8
  become: true
  pip:
    name: pep8

- name: Instalar pre-commit
  become: true
  pip:
    name: pre-commit

# Instalar lint hooks
- name: Limpiar carpeta
  file:
    path: /home/{{ remote_regular_user }}/lint-hook
    state: absent
    force: true

- name: Clonar repositorio
  git:
    repo: https://github.com/OCA/maintainer-quality-tools
    dest: /home/{{ remote_regular_user }}/lint-hook
    version: master

- name: Instalar requirements
  pip:
    chdir: /home/{{ remote_regular_user }}/lint-hook
    requirements: requirements.txt

# Fix pendiente: Usar módulo name y no command
# - name: Crear link simbólico
#   file:
#     src: /home/{{ remote_regular_user }}/lint-hook/*
#     dest: /usr/share/git-core/templates/hooks/
#     state: link
#     force: true

- name: Crear link simbólico con comando
  command: ln -sf /home/{{ remote_regular_user }}/lint-hook/git/* /usr/share/git-core/templates/hooks
  changed_when: false
