---
- name: Instalar pip3
  become: true
  apt:
    name: python3-pip

- name: Instalar PyLint for Python 3
  become: true
  apt:
    name: pylint3
    state: present

- name: Instalar pylint for odoo
  pip:
    name: pylint-odoo
    extra_args: --upgrade --pre

- name: Instalar flake8
  become: true
  pip:
    name: flake8

- name: Instalar pep8
  become: true
  pip:
    name: pep8

- name: Instalar pre-commit
  become: true
  pip:
    name: pre-commit

# Install lint hook
- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/OCA/maintainer-quality-tools.git'
    dest: /srv/checkout
    version: release-0.22

        rm -rf ${HOME}/lint-hook
        git clone https://github.com/OCA/maintainer-quality-tools ${HOME}/lint-hook
        cd ${HOME}/lint-hook
        sudo pip2 install -r requirements.txt
        sudo ln -sf ${HOME}/lint-hook/git/* /usr/share/git-core/templates/hooks
        cd ${INSTALLDIR}