---
- name: Instalar pip3, PyLint, docker-compose
  become: true
  apt:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - python3-pip
    - pylint3
    - docker-compose

- name: Instalar pylint-odoo, flake8, pep8, pre-commit
  become: true
  pip:
    name: "{{ items }}"
    extra_args: --upgrade --pre
  vars:
    items:
      - pylint-odoo
      - flake8
      - pep8
      - pre-commit

# Instalar lint hooks
- name: Limpiar carpeta
  file:
    path: /home/{{ remote_regular_user }}/lint-hook
    state: absent
    force: true

- name: Clonar repositorio
  git:
    repo: https://github.com/OCA/maintainer-quality-tools
    dest: /home/{{ remote_regular_user }}/lint-hook
    version: master

- name: Instalar requirements
  pip:
    chdir: /home/{{ remote_regular_user }}/lint-hook
    requirements: requirements.txt

# Fix pendiente: Usar módulo name y no command
# - name: Crear link simbólico
#   file:
#     src: /home/{{ remote_regular_user }}/lint-hook/*
#     dest: /usr/share/git-core/templates/hooks/
#     state: link
#     force: true

- name: Crear link simbólico con comando
  command: ln -sf /home/{{ remote_regular_user }}/lint-hook/git/* /usr/share/git-core/templates/hooks
  changed_when: false
