#    PrintMsg "Installing Rancher 0.6"
#    wget https://github.com/rancher/cli/releases/download/v0.6.13/rancher-linux-amd64-v0.6.13.tar.gz
#    tar xf rancher-linux-amd64-v0.6.13.tar.gz
#    rm rancher-linux-amd64-v0.6.13.tar.gz
#    sudo mv rancher-v0.6.13/rancher /usr/bin/rancher
#    rm -d rancher-v0.6.13/
#    # https://rancher.com/docs/rancher/v1.6/en/cli/
#    ReadLine "Please enter Rancher access-key:" RANCHER_AC_KEY
#    ReadLine "Please enter Rancher secret-key:" RANCHER_SE_KEY
#    if [[ "$RANCHER_AC_KEY" != "" && "$RANCHER_SE_KEY" != "" ]]; then
#        rancher --url https://ra.adhoc.com.ar/v1 --access-key $RANCHER_AC_KEY --secret-key $RANCHER_SE_KEY
#    fi