---
- name: Descargar binario y extraer
  ansible.builtin.unarchive:
    src: https://github.com/rancher/cli/releases/download/{{ rancher2_version }}/rancher-linux-amd64-{{ rancher2_version }}.tar.xz
    dest: /tmp
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "744"
    remote_src: true

- name: Mover binario al path
  copy:
    src: /tmp/rancher-{{ rancher2_version }}/rancher
    dest: /usr/bin/rancher2
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "744"

- name: Eliminar directorio temporal
  file:
    path: /tmp/rancher-{{ rancher2_version }}
    state: absent

- name: Descargar script r2
  copy:
    src: files/rke_byadhoc.sh
    dest: /home/{{ remote_regular_user }}/.rke_byadhoc.sh
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "744"
